export enum PropertieTypes {
    createdInPlatformVersion = "Created in platform version",
    currentPlatformVersion = "Current platform version",
    isEditableOnDoubleClick = "isEditableOnDoubleClick",
    isEnabledNewConnetion = "Is enabled new connetion",
    isAcceptingConnections = "isAcceptingConnections",
    platformVersion = "Platform version",
    isEditingTitle = "isEditingTitle",
    defaultValue = "Default value",
    parametersIn = "Parameters in",
    pathComplete = "Path complete",
    flowItemType = "flowItemType",
    updatedDate = "Updated date",
    ascendantId = "Ascendant id",
    createdDate = "Created date",
    description = "Description",
    isSelected = "Is selected",
    isExpanded = "Is expanded",
    sourceList = "Source list",
    isDisabled = "Is disabled",
    httpMethod = "Http method",
    isEditing = "Is editing",
    condition = "Condition",
    dataType = "Data type",
    required = "Required",
    comment = "Comment",
    assigns = "Assigns",
    version = "Version",
    author = "Author",
    action = "Action",
    height = "Height",
    ordem = "ordem",
    param = "Param",
    label = "Label",
    value = "Value",
    width = "Width",
    name = "Name",
    type = "Type",
    icon = "Icon",
    left = "Left",
    path = "Path",
    url = "Url",
    top = "Top",
}

export const PropertieTypesList: PropertieTypes[] = [
    PropertieTypes.createdInPlatformVersion,
    PropertieTypes.currentPlatformVersion,
    PropertieTypes.isEnabledNewConnetion,
    PropertieTypes.pathComplete,
    PropertieTypes.defaultValue,
    PropertieTypes.parametersIn,
    PropertieTypes.flowItemType,
    PropertieTypes.ascendantId,
    PropertieTypes.updatedDate,
    PropertieTypes.createdDate,
    PropertieTypes.description,
    PropertieTypes.isDisabled,
    PropertieTypes.sourceList,
    PropertieTypes.isSelected,
    PropertieTypes.isExpanded,
    PropertieTypes.isEditing,
    PropertieTypes.condition,
    PropertieTypes.required,
    PropertieTypes.dataType,
    PropertieTypes.assigns,
    PropertieTypes.comment,
    PropertieTypes.height,
    PropertieTypes.action,
    PropertieTypes.width,
    PropertieTypes.ordem,
    PropertieTypes.param,
    PropertieTypes.value,
    PropertieTypes.label,
    PropertieTypes.name,
    PropertieTypes.type,
    PropertieTypes.icon,
    PropertieTypes.left,
    PropertieTypes.url,
    PropertieTypes.top,
];
