export enum PropertieTypes {
    defaultValue="Default value",
    parametersIn="Parameters in",
    description="Description",
    sourceList="Source list",
    condiction="Condiction",
    dataType="Data type",
    required="Required",
    comment="Comment",
    assigns="Assigns",
    action="Action",
    param="Param",
    label="Label",
    value="Value",
    name="Name",
    type="Type",
    icon="Icon",
    url="Url",
}

export const PropertieTypesList: PropertieTypes[] = [
    PropertieTypes.defaultValue,
    PropertieTypes.parametersIn,
    PropertieTypes.description,
    PropertieTypes.sourceList,
    PropertieTypes.condiction,
    PropertieTypes.required,
    PropertieTypes.dataType,
    PropertieTypes.assigns,
    PropertieTypes.comment,
    PropertieTypes.action,
    PropertieTypes.param,
    PropertieTypes.value,
    PropertieTypes.label,
    PropertieTypes.name,
    PropertieTypes.type,
    PropertieTypes.icon,
    PropertieTypes.url,
];
